package certmaterial

import (
	"bytes"
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"flag"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// Test fixtures (T006). The PEM files under testdata/ are generated by
//
//	go test ./internal/certmaterial -run TestFixtures -update-fixtures
//
// and committed, so agent and deployer tests can use the same vectors
// (the deployer copies them into its inventoryagent/testdata). They are
// throw-away test keys with fixed validity windows:
//
//	root.pem, intermediate.pem      CA certificates (2025-01-01 .. 2040-01-01)
//	chain.pem                       intermediate + root (2-level chain)
//	rsa.crt + rsa.pkcs8.key, rsa.pkcs1.key          RSA-2048 leaf
//	ecdsa.crt + ecdsa.pkcs8.key, ecdsa.sec1.key     ECDSA P-256 leaf
//	ed25519.crt + ed25519.key                       Ed25519 leaf (PKCS#8)
//	expired.crt + expired.key       valid 2020-01-01 .. 2021-01-01
//	notyet.crt + notyet.key         valid 2090-01-01 .. 2091-01-01
//	mismatch.key                    an ECDSA key matching no certificate
//	chain-11.pem                    11 CA certificates (over the chain limit)
//
// Leaves are valid 2026-01-01 .. 2036-01-01 with CN www.example.com and
// SANs www.example.com, example.com, 192.0.2.10, 2001:db8::1.
var updateFixtures = flag.Bool("update-fixtures", false, "regenerate internal/certmaterial/testdata")

// fixtureNow is inside every leaf's validity window.
var fixtureNow = time.Date(2026, 6, 1, 0, 0, 0, 0, time.UTC)

func fixedNow() time.Time { return fixtureNow }

var fixtureFiles = []string{
	"root.pem", "intermediate.pem", "chain.pem",
	"rsa.crt", "rsa.pkcs8.key", "rsa.pkcs1.key",
	"ecdsa.crt", "ecdsa.pkcs8.key", "ecdsa.sec1.key",
	"ed25519.crt", "ed25519.key",
	"expired.crt", "expired.key", "notyet.crt", "notyet.key",
	"mismatch.key", "chain-11.pem",
}

// fixture returns the content of testdata/<name>.
func fixture(t testing.TB, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name)) // #nosec G304 -- test fixture
	if err != nil {
		t.Fatalf("fixture %s: %v (regenerate with -update-fixtures)", name, err)
	}
	return b
}

func TestFixtures(t *testing.T) {
	if *updateFixtures {
		writeFixtures(t)
	}
	for _, f := range fixtureFiles {
		if len(fixture(t, f)) == 0 {
			t.Fatalf("fixture %s is empty", f)
		}
	}
	// The committed vectors stay consistent with what the tests assume.
	chain := fixture(t, "chain.pem")
	for _, leaf := range []string{"rsa", "ecdsa", "ed25519"} {
		b, err := ParseBundle(fixture(t, leaf+".crt"), chain, fixture(t, keyFile(leaf)), Options{RequireKey: true, Now: fixedNow})
		if err != nil {
			t.Fatalf("%s: %v", leaf, err)
		}
		if b.CommonName != "www.example.com" || len(b.Chain) != 2 {
			t.Fatalf("%s: unexpected fixture %+v", leaf, b.CommonName)
		}
	}
}

func keyFile(leaf string) string {
	if leaf == "ed25519" {
		return "ed25519.key"
	}
	return leaf + ".pkcs8.key"
}

// ---- generator (runs only with -update-fixtures)

func writeFixtures(t *testing.T) {
	t.Helper()
	caFrom := time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)
	caTo := time.Date(2040, 1, 1, 0, 0, 0, 0, time.UTC)
	leafFrom := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	leafTo := time.Date(2036, 1, 1, 0, 0, 0, 0, time.UTC)

	rootKey := mustECDSA(t)
	root := mustCert(t, caTemplate(1, "Fixture Root CA", caFrom, caTo), nil, rootKey.Public(), rootKey)
	interKey := mustECDSA(t)
	inter := mustCert(t, caTemplate(2, "Fixture Issuing CA", caFrom, caTo), root, interKey.Public(), rootKey)

	out := map[string][]byte{
		"root.pem":         certPEM(root),
		"intermediate.pem": certPEM(inter),
		"chain.pem":        append(certPEM(inter), certPEM(root)...),
	}

	rsaKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		t.Fatal(err)
	}
	out["rsa.crt"] = certPEM(mustCert(t, leafTemplate(10, leafFrom, leafTo), inter, rsaKey.Public(), interKey))
	out["rsa.pkcs8.key"] = pkcs8PEM(t, rsaKey)
	out["rsa.pkcs1.key"] = pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(rsaKey)})

	ecKey := mustECDSA(t)
	out["ecdsa.crt"] = certPEM(mustCert(t, leafTemplate(11, leafFrom, leafTo), inter, ecKey.Public(), interKey))
	out["ecdsa.pkcs8.key"] = pkcs8PEM(t, ecKey)
	sec1, err := x509.MarshalECPrivateKey(ecKey)
	if err != nil {
		t.Fatal(err)
	}
	out["ecdsa.sec1.key"] = pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: sec1})

	_, edKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	out["ed25519.crt"] = certPEM(mustCert(t, leafTemplate(12, leafFrom, leafTo), inter, edKey.Public(), interKey))
	out["ed25519.key"] = pkcs8PEM(t, edKey)

	expKey := mustECDSA(t)
	out["expired.crt"] = certPEM(mustCert(t, leafTemplate(13, time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC),
		time.Date(2021, 1, 1, 0, 0, 0, 0, time.UTC)), inter, expKey.Public(), interKey))
	out["expired.key"] = pkcs8PEM(t, expKey)

	nyKey := mustECDSA(t)
	out["notyet.crt"] = certPEM(mustCert(t, leafTemplate(14, time.Date(2090, 1, 1, 0, 0, 0, 0, time.UTC),
		time.Date(2091, 1, 1, 0, 0, 0, 0, time.UTC)), inter, nyKey.Public(), interKey))
	out["notyet.key"] = pkcs8PEM(t, nyKey)

	out["mismatch.key"] = pkcs8PEM(t, mustECDSA(t))

	var long bytes.Buffer
	for i := 0; i < 11; i++ {
		k := mustECDSA(t)
		long.Write(certPEM(mustCert(t, caTemplate(int64(100+i), "Fixture Filler CA", caFrom, caTo), nil, k.Public(), k)))
	}
	out["chain-11.pem"] = long.Bytes()

	for name, data := range out {
		if err := os.WriteFile(filepath.Join("testdata", name), data, 0o600); err != nil {
			t.Fatal(err)
		}
	}
}

func mustECDSA(t *testing.T) *ecdsa.PrivateKey {
	t.Helper()
	k, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	return k
}

func caTemplate(serial int64, cn string, from, to time.Time) *x509.Certificate {
	return &x509.Certificate{
		SerialNumber: big.NewInt(serial), Subject: pkix.Name{CommonName: cn},
		NotBefore: from, NotAfter: to, IsCA: true, BasicConstraintsValid: true,
		KeyUsage: x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
	}
}

func leafTemplate(serial int64, from, to time.Time) *x509.Certificate {
	return &x509.Certificate{
		SerialNumber: new(big.Int).Lsh(big.NewInt(serial), 64), Subject: pkix.Name{CommonName: "www.example.com"},
		NotBefore: from, NotAfter: to,
		DNSNames:    []string{"www.example.com", "example.com"},
		IPAddresses: []net.IP{net.ParseIP("192.0.2.10"), net.ParseIP("2001:db8::1")},
		KeyUsage:    x509.KeyUsageDigitalSignature, ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
}

func mustCert(t *testing.T, tmpl, parent *x509.Certificate, pub crypto.PublicKey, signer crypto.Signer) *x509.Certificate {
	t.Helper()
	if parent == nil {
		parent = tmpl
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, parent, pub, signer)
	if err != nil {
		t.Fatal(err)
	}
	c, err := x509.ParseCertificate(der)
	if err != nil {
		t.Fatal(err)
	}
	return c
}

func certPEM(c *x509.Certificate) []byte {
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: c.Raw})
}

func pkcs8PEM(t *testing.T, k any) []byte {
	t.Helper()
	der, err := x509.MarshalPKCS8PrivateKey(k)
	if err != nil {
		t.Fatal(err)
	}
	return pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der})
}
