// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: inventory/v1/inventory.proto

// inventory.v1 carries two related surfaces of the inventory module:
//
//   * The module-to-module API (InventoryHostService, InventorySnapshotService,
//     InventoryStatisticsService, InventoryAgentService). It is NOT proxied by
//     the gateway: callers are authenticated platform services on the Freya
//     SPIFFE mTLS channel, acting for the tenant named in each request
//     (tenant_id). The actor identity comes from the verified SPIFFE peer.
//
//   * The off-mesh ingest edge (IngestService), served on a dedicated listener
//     network-isolated from the mesh, where endpoint agents authenticate with a
//     per-agent sealed credential presented in call metadata.
//
// Redaction: no message ever carries an agent's sealed credential or an
// enrollment-token secret, with the single deliberate exception of
// EnrollResponse.agent_credential (issued exactly once at enrollment) and
// MintEnrollmentTokenResponse.token (the mint secret, returned exactly once).
// Snapshot and host messages exclude sealed fields and are safe to log.

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryHostService_ListHosts_FullMethodName         = "/inventory.v1.InventoryHostService/ListHosts"
	InventoryHostService_GetHost_FullMethodName           = "/inventory.v1.InventoryHostService/GetHost"
	InventoryHostService_GetHostByIdentity_FullMethodName = "/inventory.v1.InventoryHostService/GetHostByIdentity"
	InventoryHostService_TagHost_FullMethodName           = "/inventory.v1.InventoryHostService/TagHost"
	InventoryHostService_RetireHost_FullMethodName        = "/inventory.v1.InventoryHostService/RetireHost"
	InventoryHostService_DeleteHost_FullMethodName        = "/inventory.v1.InventoryHostService/DeleteHost"
)

// InventoryHostServiceClient is the client API for InventoryHostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryHostService reads and administers hosts for platform services.
type InventoryHostServiceClient interface {
	ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error)
	GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*Host, error)
	GetHostByIdentity(ctx context.Context, in *GetHostByIdentityRequest, opts ...grpc.CallOption) (*Host, error)
	TagHost(ctx context.Context, in *TagHostRequest, opts ...grpc.CallOption) (*Host, error)
	RetireHost(ctx context.Context, in *RetireHostRequest, opts ...grpc.CallOption) (*Host, error)
	DeleteHost(ctx context.Context, in *DeleteHostRequest, opts ...grpc.CallOption) (*DeleteHostResponse, error)
}

type inventoryHostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryHostServiceClient(cc grpc.ClientConnInterface) InventoryHostServiceClient {
	return &inventoryHostServiceClient{cc}
}

func (c *inventoryHostServiceClient) ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHostsResponse)
	err := c.cc.Invoke(ctx, InventoryHostService_ListHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryHostServiceClient) GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*Host, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Host)
	err := c.cc.Invoke(ctx, InventoryHostService_GetHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryHostServiceClient) GetHostByIdentity(ctx context.Context, in *GetHostByIdentityRequest, opts ...grpc.CallOption) (*Host, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Host)
	err := c.cc.Invoke(ctx, InventoryHostService_GetHostByIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryHostServiceClient) TagHost(ctx context.Context, in *TagHostRequest, opts ...grpc.CallOption) (*Host, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Host)
	err := c.cc.Invoke(ctx, InventoryHostService_TagHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryHostServiceClient) RetireHost(ctx context.Context, in *RetireHostRequest, opts ...grpc.CallOption) (*Host, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Host)
	err := c.cc.Invoke(ctx, InventoryHostService_RetireHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryHostServiceClient) DeleteHost(ctx context.Context, in *DeleteHostRequest, opts ...grpc.CallOption) (*DeleteHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHostResponse)
	err := c.cc.Invoke(ctx, InventoryHostService_DeleteHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryHostServiceServer is the server API for InventoryHostService service.
// All implementations must embed UnimplementedInventoryHostServiceServer
// for forward compatibility.
//
// InventoryHostService reads and administers hosts for platform services.
type InventoryHostServiceServer interface {
	ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error)
	GetHost(context.Context, *GetHostRequest) (*Host, error)
	GetHostByIdentity(context.Context, *GetHostByIdentityRequest) (*Host, error)
	TagHost(context.Context, *TagHostRequest) (*Host, error)
	RetireHost(context.Context, *RetireHostRequest) (*Host, error)
	DeleteHost(context.Context, *DeleteHostRequest) (*DeleteHostResponse, error)
	mustEmbedUnimplementedInventoryHostServiceServer()
}

// UnimplementedInventoryHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryHostServiceServer struct{}

func (UnimplementedInventoryHostServiceServer) ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHosts not implemented")
}
func (UnimplementedInventoryHostServiceServer) GetHost(context.Context, *GetHostRequest) (*Host, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHost not implemented")
}
func (UnimplementedInventoryHostServiceServer) GetHostByIdentity(context.Context, *GetHostByIdentityRequest) (*Host, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostByIdentity not implemented")
}
func (UnimplementedInventoryHostServiceServer) TagHost(context.Context, *TagHostRequest) (*Host, error) {
	return nil, status.Error(codes.Unimplemented, "method TagHost not implemented")
}
func (UnimplementedInventoryHostServiceServer) RetireHost(context.Context, *RetireHostRequest) (*Host, error) {
	return nil, status.Error(codes.Unimplemented, "method RetireHost not implemented")
}
func (UnimplementedInventoryHostServiceServer) DeleteHost(context.Context, *DeleteHostRequest) (*DeleteHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHost not implemented")
}
func (UnimplementedInventoryHostServiceServer) mustEmbedUnimplementedInventoryHostServiceServer() {}
func (UnimplementedInventoryHostServiceServer) testEmbeddedByValue()                              {}

// UnsafeInventoryHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryHostServiceServer will
// result in compilation errors.
type UnsafeInventoryHostServiceServer interface {
	mustEmbedUnimplementedInventoryHostServiceServer()
}

func RegisterInventoryHostServiceServer(s grpc.ServiceRegistrar, srv InventoryHostServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryHostService_ServiceDesc, srv)
}

func _InventoryHostService_ListHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryHostServiceServer).ListHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryHostService_ListHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryHostServiceServer).ListHosts(ctx, req.(*ListHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryHostService_GetHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryHostServiceServer).GetHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryHostService_GetHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryHostServiceServer).GetHost(ctx, req.(*GetHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryHostService_GetHostByIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostByIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryHostServiceServer).GetHostByIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryHostService_GetHostByIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryHostServiceServer).GetHostByIdentity(ctx, req.(*GetHostByIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryHostService_TagHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryHostServiceServer).TagHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryHostService_TagHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryHostServiceServer).TagHost(ctx, req.(*TagHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryHostService_RetireHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetireHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryHostServiceServer).RetireHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryHostService_RetireHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryHostServiceServer).RetireHost(ctx, req.(*RetireHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryHostService_DeleteHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryHostServiceServer).DeleteHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryHostService_DeleteHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryHostServiceServer).DeleteHost(ctx, req.(*DeleteHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryHostService_ServiceDesc is the grpc.ServiceDesc for InventoryHostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryHostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryHostService",
	HandlerType: (*InventoryHostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHosts",
			Handler:    _InventoryHostService_ListHosts_Handler,
		},
		{
			MethodName: "GetHost",
			Handler:    _InventoryHostService_GetHost_Handler,
		},
		{
			MethodName: "GetHostByIdentity",
			Handler:    _InventoryHostService_GetHostByIdentity_Handler,
		},
		{
			MethodName: "TagHost",
			Handler:    _InventoryHostService_TagHost_Handler,
		},
		{
			MethodName: "RetireHost",
			Handler:    _InventoryHostService_RetireHost_Handler,
		},
		{
			MethodName: "DeleteHost",
			Handler:    _InventoryHostService_DeleteHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}

const (
	InventorySnapshotService_GetSnapshot_FullMethodName     = "/inventory.v1.InventorySnapshotService/GetSnapshot"
	InventorySnapshotService_ListSnapshots_FullMethodName   = "/inventory.v1.InventorySnapshotService/ListSnapshots"
	InventorySnapshotService_GetLatestByHost_FullMethodName = "/inventory.v1.InventorySnapshotService/GetLatestByHost"
	InventorySnapshotService_DiffSnapshots_FullMethodName   = "/inventory.v1.InventorySnapshotService/DiffSnapshots"
	InventorySnapshotService_ListChanges_FullMethodName     = "/inventory.v1.InventorySnapshotService/ListChanges"
	InventorySnapshotService_DeleteSnapshot_FullMethodName  = "/inventory.v1.InventorySnapshotService/DeleteSnapshot"
)

// InventorySnapshotServiceClient is the client API for InventorySnapshotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventorySnapshotService reads snapshot history, diffs and change records.
type InventorySnapshotServiceClient interface {
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error)
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	GetLatestByHost(ctx context.Context, in *GetLatestByHostRequest, opts ...grpc.CallOption) (*Snapshot, error)
	DiffSnapshots(ctx context.Context, in *DiffSnapshotsRequest, opts ...grpc.CallOption) (*DiffSnapshotsResponse, error)
	ListChanges(ctx context.Context, in *ListChangesRequest, opts ...grpc.CallOption) (*ListChangesResponse, error)
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
}

type inventorySnapshotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventorySnapshotServiceClient(cc grpc.ClientConnInterface) InventorySnapshotServiceClient {
	return &inventorySnapshotServiceClient{cc}
}

func (c *inventorySnapshotServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, InventorySnapshotService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventorySnapshotServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, InventorySnapshotService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventorySnapshotServiceClient) GetLatestByHost(ctx context.Context, in *GetLatestByHostRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, InventorySnapshotService_GetLatestByHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventorySnapshotServiceClient) DiffSnapshots(ctx context.Context, in *DiffSnapshotsRequest, opts ...grpc.CallOption) (*DiffSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffSnapshotsResponse)
	err := c.cc.Invoke(ctx, InventorySnapshotService_DiffSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventorySnapshotServiceClient) ListChanges(ctx context.Context, in *ListChangesRequest, opts ...grpc.CallOption) (*ListChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChangesResponse)
	err := c.cc.Invoke(ctx, InventorySnapshotService_ListChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventorySnapshotServiceClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, InventorySnapshotService_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventorySnapshotServiceServer is the server API for InventorySnapshotService service.
// All implementations must embed UnimplementedInventorySnapshotServiceServer
// for forward compatibility.
//
// InventorySnapshotService reads snapshot history, diffs and change records.
type InventorySnapshotServiceServer interface {
	GetSnapshot(context.Context, *GetSnapshotRequest) (*Snapshot, error)
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	GetLatestByHost(context.Context, *GetLatestByHostRequest) (*Snapshot, error)
	DiffSnapshots(context.Context, *DiffSnapshotsRequest) (*DiffSnapshotsResponse, error)
	ListChanges(context.Context, *ListChangesRequest) (*ListChangesResponse, error)
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	mustEmbedUnimplementedInventorySnapshotServiceServer()
}

// UnimplementedInventorySnapshotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventorySnapshotServiceServer struct{}

func (UnimplementedInventorySnapshotServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*Snapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedInventorySnapshotServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedInventorySnapshotServiceServer) GetLatestByHost(context.Context, *GetLatestByHostRequest) (*Snapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestByHost not implemented")
}
func (UnimplementedInventorySnapshotServiceServer) DiffSnapshots(context.Context, *DiffSnapshotsRequest) (*DiffSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiffSnapshots not implemented")
}
func (UnimplementedInventorySnapshotServiceServer) ListChanges(context.Context, *ListChangesRequest) (*ListChangesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChanges not implemented")
}
func (UnimplementedInventorySnapshotServiceServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedInventorySnapshotServiceServer) mustEmbedUnimplementedInventorySnapshotServiceServer() {
}
func (UnimplementedInventorySnapshotServiceServer) testEmbeddedByValue() {}

// UnsafeInventorySnapshotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventorySnapshotServiceServer will
// result in compilation errors.
type UnsafeInventorySnapshotServiceServer interface {
	mustEmbedUnimplementedInventorySnapshotServiceServer()
}

func RegisterInventorySnapshotServiceServer(s grpc.ServiceRegistrar, srv InventorySnapshotServiceServer) {
	// If the following call panics, it indicates UnimplementedInventorySnapshotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventorySnapshotService_ServiceDesc, srv)
}

func _InventorySnapshotService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventorySnapshotServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventorySnapshotService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventorySnapshotServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventorySnapshotService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventorySnapshotServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventorySnapshotService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventorySnapshotServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventorySnapshotService_GetLatestByHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestByHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventorySnapshotServiceServer).GetLatestByHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventorySnapshotService_GetLatestByHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventorySnapshotServiceServer).GetLatestByHost(ctx, req.(*GetLatestByHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventorySnapshotService_DiffSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventorySnapshotServiceServer).DiffSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventorySnapshotService_DiffSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventorySnapshotServiceServer).DiffSnapshots(ctx, req.(*DiffSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventorySnapshotService_ListChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventorySnapshotServiceServer).ListChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventorySnapshotService_ListChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventorySnapshotServiceServer).ListChanges(ctx, req.(*ListChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventorySnapshotService_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventorySnapshotServiceServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventorySnapshotService_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventorySnapshotServiceServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventorySnapshotService_ServiceDesc is the grpc.ServiceDesc for InventorySnapshotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventorySnapshotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventorySnapshotService",
	HandlerType: (*InventorySnapshotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSnapshot",
			Handler:    _InventorySnapshotService_GetSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _InventorySnapshotService_ListSnapshots_Handler,
		},
		{
			MethodName: "GetLatestByHost",
			Handler:    _InventorySnapshotService_GetLatestByHost_Handler,
		},
		{
			MethodName: "DiffSnapshots",
			Handler:    _InventorySnapshotService_DiffSnapshots_Handler,
		},
		{
			MethodName: "ListChanges",
			Handler:    _InventorySnapshotService_ListChanges_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _InventorySnapshotService_DeleteSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}

const (
	InventoryStatisticsService_GetStatistics_FullMethodName = "/inventory.v1.InventoryStatisticsService/GetStatistics"
)

// InventoryStatisticsServiceClient is the client API for InventoryStatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryStatisticsService reports per-tenant inventory rollups.
type InventoryStatisticsServiceClient interface {
	GetStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*Stats, error)
}

type inventoryStatisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryStatisticsServiceClient(cc grpc.ClientConnInterface) InventoryStatisticsServiceClient {
	return &inventoryStatisticsServiceClient{cc}
}

func (c *inventoryStatisticsServiceClient) GetStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*Stats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Stats)
	err := c.cc.Invoke(ctx, InventoryStatisticsService_GetStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryStatisticsServiceServer is the server API for InventoryStatisticsService service.
// All implementations must embed UnimplementedInventoryStatisticsServiceServer
// for forward compatibility.
//
// InventoryStatisticsService reports per-tenant inventory rollups.
type InventoryStatisticsServiceServer interface {
	GetStatistics(context.Context, *GetStatisticsRequest) (*Stats, error)
	mustEmbedUnimplementedInventoryStatisticsServiceServer()
}

// UnimplementedInventoryStatisticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryStatisticsServiceServer struct{}

func (UnimplementedInventoryStatisticsServiceServer) GetStatistics(context.Context, *GetStatisticsRequest) (*Stats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatistics not implemented")
}
func (UnimplementedInventoryStatisticsServiceServer) mustEmbedUnimplementedInventoryStatisticsServiceServer() {
}
func (UnimplementedInventoryStatisticsServiceServer) testEmbeddedByValue() {}

// UnsafeInventoryStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryStatisticsServiceServer will
// result in compilation errors.
type UnsafeInventoryStatisticsServiceServer interface {
	mustEmbedUnimplementedInventoryStatisticsServiceServer()
}

func RegisterInventoryStatisticsServiceServer(s grpc.ServiceRegistrar, srv InventoryStatisticsServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryStatisticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryStatisticsService_ServiceDesc, srv)
}

func _InventoryStatisticsService_GetStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryStatisticsServiceServer).GetStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryStatisticsService_GetStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryStatisticsServiceServer).GetStatistics(ctx, req.(*GetStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryStatisticsService_ServiceDesc is the grpc.ServiceDesc for InventoryStatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryStatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryStatisticsService",
	HandlerType: (*InventoryStatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatistics",
			Handler:    _InventoryStatisticsService_GetStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}

const (
	InventoryAgentService_ListConnectedAgents_FullMethodName = "/inventory.v1.InventoryAgentService/ListConnectedAgents"
	InventoryAgentService_RefreshInventory_FullMethodName    = "/inventory.v1.InventoryAgentService/RefreshInventory"
	InventoryAgentService_MintEnrollmentToken_FullMethodName = "/inventory.v1.InventoryAgentService/MintEnrollmentToken"
	InventoryAgentService_RevokeAgent_FullMethodName         = "/inventory.v1.InventoryAgentService/RevokeAgent"
)

// InventoryAgentServiceClient is the client API for InventoryAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryAgentService is the operator surface over agents and enrollment.
type InventoryAgentServiceClient interface {
	ListConnectedAgents(ctx context.Context, in *ListConnectedAgentsRequest, opts ...grpc.CallOption) (*ListConnectedAgentsResponse, error)
	RefreshInventory(ctx context.Context, in *RefreshInventoryRequest, opts ...grpc.CallOption) (*RefreshInventoryResponse, error)
	MintEnrollmentToken(ctx context.Context, in *MintEnrollmentTokenRequest, opts ...grpc.CallOption) (*MintEnrollmentTokenResponse, error)
	RevokeAgent(ctx context.Context, in *RevokeAgentRequest, opts ...grpc.CallOption) (*RevokeAgentResponse, error)
}

type inventoryAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryAgentServiceClient(cc grpc.ClientConnInterface) InventoryAgentServiceClient {
	return &inventoryAgentServiceClient{cc}
}

func (c *inventoryAgentServiceClient) ListConnectedAgents(ctx context.Context, in *ListConnectedAgentsRequest, opts ...grpc.CallOption) (*ListConnectedAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectedAgentsResponse)
	err := c.cc.Invoke(ctx, InventoryAgentService_ListConnectedAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryAgentServiceClient) RefreshInventory(ctx context.Context, in *RefreshInventoryRequest, opts ...grpc.CallOption) (*RefreshInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryAgentService_RefreshInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryAgentServiceClient) MintEnrollmentToken(ctx context.Context, in *MintEnrollmentTokenRequest, opts ...grpc.CallOption) (*MintEnrollmentTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintEnrollmentTokenResponse)
	err := c.cc.Invoke(ctx, InventoryAgentService_MintEnrollmentToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryAgentServiceClient) RevokeAgent(ctx context.Context, in *RevokeAgentRequest, opts ...grpc.CallOption) (*RevokeAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAgentResponse)
	err := c.cc.Invoke(ctx, InventoryAgentService_RevokeAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryAgentServiceServer is the server API for InventoryAgentService service.
// All implementations must embed UnimplementedInventoryAgentServiceServer
// for forward compatibility.
//
// InventoryAgentService is the operator surface over agents and enrollment.
type InventoryAgentServiceServer interface {
	ListConnectedAgents(context.Context, *ListConnectedAgentsRequest) (*ListConnectedAgentsResponse, error)
	RefreshInventory(context.Context, *RefreshInventoryRequest) (*RefreshInventoryResponse, error)
	MintEnrollmentToken(context.Context, *MintEnrollmentTokenRequest) (*MintEnrollmentTokenResponse, error)
	RevokeAgent(context.Context, *RevokeAgentRequest) (*RevokeAgentResponse, error)
	mustEmbedUnimplementedInventoryAgentServiceServer()
}

// UnimplementedInventoryAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryAgentServiceServer struct{}

func (UnimplementedInventoryAgentServiceServer) ListConnectedAgents(context.Context, *ListConnectedAgentsRequest) (*ListConnectedAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnectedAgents not implemented")
}
func (UnimplementedInventoryAgentServiceServer) RefreshInventory(context.Context, *RefreshInventoryRequest) (*RefreshInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshInventory not implemented")
}
func (UnimplementedInventoryAgentServiceServer) MintEnrollmentToken(context.Context, *MintEnrollmentTokenRequest) (*MintEnrollmentTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintEnrollmentToken not implemented")
}
func (UnimplementedInventoryAgentServiceServer) RevokeAgent(context.Context, *RevokeAgentRequest) (*RevokeAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAgent not implemented")
}
func (UnimplementedInventoryAgentServiceServer) mustEmbedUnimplementedInventoryAgentServiceServer() {}
func (UnimplementedInventoryAgentServiceServer) testEmbeddedByValue()                               {}

// UnsafeInventoryAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryAgentServiceServer will
// result in compilation errors.
type UnsafeInventoryAgentServiceServer interface {
	mustEmbedUnimplementedInventoryAgentServiceServer()
}

func RegisterInventoryAgentServiceServer(s grpc.ServiceRegistrar, srv InventoryAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryAgentService_ServiceDesc, srv)
}

func _InventoryAgentService_ListConnectedAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectedAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryAgentServiceServer).ListConnectedAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryAgentService_ListConnectedAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryAgentServiceServer).ListConnectedAgents(ctx, req.(*ListConnectedAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryAgentService_RefreshInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryAgentServiceServer).RefreshInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryAgentService_RefreshInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryAgentServiceServer).RefreshInventory(ctx, req.(*RefreshInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryAgentService_MintEnrollmentToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintEnrollmentTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryAgentServiceServer).MintEnrollmentToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryAgentService_MintEnrollmentToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryAgentServiceServer).MintEnrollmentToken(ctx, req.(*MintEnrollmentTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryAgentService_RevokeAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryAgentServiceServer).RevokeAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryAgentService_RevokeAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryAgentServiceServer).RevokeAgent(ctx, req.(*RevokeAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryAgentService_ServiceDesc is the grpc.ServiceDesc for InventoryAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryAgentService",
	HandlerType: (*InventoryAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConnectedAgents",
			Handler:    _InventoryAgentService_ListConnectedAgents_Handler,
		},
		{
			MethodName: "RefreshInventory",
			Handler:    _InventoryAgentService_RefreshInventory_Handler,
		},
		{
			MethodName: "MintEnrollmentToken",
			Handler:    _InventoryAgentService_MintEnrollmentToken_Handler,
		},
		{
			MethodName: "RevokeAgent",
			Handler:    _InventoryAgentService_RevokeAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}

const (
	IngestService_Enroll_FullMethodName          = "/inventory.v1.IngestService/Enroll"
	IngestService_SubmitInventory_FullMethodName = "/inventory.v1.IngestService/SubmitInventory"
	IngestService_StreamCommands_FullMethodName  = "/inventory.v1.IngestService/StreamCommands"
)

// IngestServiceClient is the client API for IngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IngestService is the off-mesh edge spoken by endpoint agents. Enroll consumes
// an enrollment token and issues the sealed per-agent credential; SubmitInventory
// and StreamCommands authenticate with that credential presented in metadata.
type IngestServiceClient interface {
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	SubmitInventory(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	StreamCommands(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error)
}

type ingestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestServiceClient(cc grpc.ClientConnInterface) IngestServiceClient {
	return &ingestServiceClient{cc}
}

func (c *ingestServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, IngestService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) SubmitInventory(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, IngestService_SubmitInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) StreamCommands(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestService_ServiceDesc.Streams[0], IngestService_StreamCommands_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, Command]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_StreamCommandsClient = grpc.ServerStreamingClient[Command]

// IngestServiceServer is the server API for IngestService service.
// All implementations must embed UnimplementedIngestServiceServer
// for forward compatibility.
//
// IngestService is the off-mesh edge spoken by endpoint agents. Enroll consumes
// an enrollment token and issues the sealed per-agent credential; SubmitInventory
// and StreamCommands authenticate with that credential presented in metadata.
type IngestServiceServer interface {
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	SubmitInventory(context.Context, *SubmitRequest) (*SubmitResponse, error)
	StreamCommands(*StreamRequest, grpc.ServerStreamingServer[Command]) error
	mustEmbedUnimplementedIngestServiceServer()
}

// UnimplementedIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestServiceServer struct{}

func (UnimplementedIngestServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedIngestServiceServer) SubmitInventory(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitInventory not implemented")
}
func (UnimplementedIngestServiceServer) StreamCommands(*StreamRequest, grpc.ServerStreamingServer[Command]) error {
	return status.Error(codes.Unimplemented, "method StreamCommands not implemented")
}
func (UnimplementedIngestServiceServer) mustEmbedUnimplementedIngestServiceServer() {}
func (UnimplementedIngestServiceServer) testEmbeddedByValue()                       {}

// UnsafeIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestServiceServer will
// result in compilation errors.
type UnsafeIngestServiceServer interface {
	mustEmbedUnimplementedIngestServiceServer()
}

func RegisterIngestServiceServer(s grpc.ServiceRegistrar, srv IngestServiceServer) {
	// If the following call panics, it indicates UnimplementedIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestService_ServiceDesc, srv)
}

func _IngestService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_SubmitInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).SubmitInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_SubmitInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).SubmitInventory(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_StreamCommands_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IngestServiceServer).StreamCommands(m, &grpc.GenericServerStream[StreamRequest, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_StreamCommandsServer = grpc.ServerStreamingServer[Command]

// IngestService_ServiceDesc is the grpc.ServiceDesc for IngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.IngestService",
	HandlerType: (*IngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _IngestService_Enroll_Handler,
		},
		{
			MethodName: "SubmitInventory",
			Handler:    _IngestService_SubmitInventory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCommands",
			Handler:       _IngestService_StreamCommands_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inventory/v1/inventory.proto",
}
