/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/inventory/v1/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/hosts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHost"];
        put?: never;
        post?: never;
        delete: operations["deleteHost"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/hosts/{id}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHostLatestSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/hosts/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setHostTags"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/hosts/{id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retireHost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/hosts/{id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHostSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/hosts/{id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHostChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/snapshots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSnapshot"];
        put?: never;
        post?: never;
        delete: operations["deleteSnapshot"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/snapshots/{id}/diff/{other}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["diffSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every enrolled agent (online and offline) with its version and upgrade state */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agents/upgrades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgentUpgrades"];
        put?: never;
        /** Upgrade one agent, a selection or every outdated agent to the tenant target version */
        post: operations["requestAgentUpgrades"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agents/upgrades/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAgentUpgrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agents/upgrade-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The tenant's automatic agent upgrade policy (defaults when none is stored) */
        get: operations["getAgentUpgradePolicy"];
        /** Configure automatic agent upgrades and the target agent version */
        put: operations["updateAgentUpgradePolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agents/upgrade-policy/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume automatic upgrades paused by a failed automatic upgrade */
        post: operations["resumeAgentUpgradePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agents/auto-enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The tenant's automatic enrollment switch and keys (secrets are never returned) */
        get: operations["getAutoEnroll"];
        /** Turn automatic enrollment on or off for the tenant */
        put: operations["setAutoEnroll"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agents/auto-enroll/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an auto-enrollment key (the secret is returned once) */
        post: operations["createAutoEnrollKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agents/auto-enroll/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an auto-enrollment key (enrolled agents keep working) */
        delete: operations["deleteAutoEnrollKey"];
        options?: never;
        head?: never;
        /** Change an auto-enrollment key (name, networks, on/off, expiry, limit) */
        patch: operations["updateAutoEnrollKey"];
        trace?: never;
    };
    "/api/inventory/v1/agents/auto-enroll/keys/{id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace the key's secret (returned once); the key id stays */
        post: operations["rotateAutoEnrollKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agent-releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signed agent releases stored on the platform */
        get: operations["listAgentReleases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agents/enroll-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mintEnrollmentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agents/{host_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshInventory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/agents/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/statistics/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTenantStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/statistics/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSystemStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/backup/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exportBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/backup/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "reason": "not_found",
         *       "detail": {}
         *     }
         */
        Error: {
            reason?: string;
            detail?: Record<string, never>;
        };
        /** @description One enrolled agent (online or not) with its upgrade state. The keys of the former connected-agents listing are kept. */
        AgentFleetEntry: {
            /**
             * @description enrollment method (feature 029)
             * @enum {string}
             */
            enrolled_via?: "token" | "auto";
            /** @description public id of the auto-enrollment key, when enrolled_via = auto */
            auto_enroll_key_id?: string;
            /** Format: uuid */
            agent_id?: string;
            /** Format: uuid */
            tenant_id?: string;
            host_id?: string;
            hostname?: string;
            version?: string;
            /** @enum {string} */
            os?: "" | "linux" | "windows";
            /** @enum {string} */
            arch?: "" | "amd64" | "arm64";
            /** @enum {string} */
            install_type?: "" | "deb" | "rpm" | "binary";
            online?: boolean;
            /** Format: date-time */
            connected_at?: string;
            /** Format: date-time */
            last_seen?: string;
            target_version?: string;
            /** @enum {string} */
            upgrade_state?: "up_to_date" | "available" | "pending" | "in_progress" | "failed" | "rolled_back" | "manual_upgrade_required" | "unsupported";
            /** @description reason code only */
            upgrade_reason?: string;
            /** Format: uuid */
            upgrade_id?: string;
            /** Format: date-time */
            state_changed_at?: string;
        };
        AgentFleet: {
            items?: components["schemas"]["AgentFleetEntry"][];
            /** @description the tenant target: policy pin or platform current agent version */
            current_version?: string;
        };
        AgentUpgrade: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            agent_id?: string;
            host_id?: string;
            from_version?: string;
            target_version?: string;
            allow_downgrade?: boolean;
            /** @enum {string} */
            state?: "pending" | "delivered" | "downloading" | "installing" | "succeeded" | "failed" | "rolled_back" | "expired" | "cancelled";
            /** @enum {string} */
            origin?: "user" | "policy" | "agent";
            requested_by?: string;
            reason?: string;
            attempts?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: date-time */
            expires_at?: string;
            /** Format: date-time */
            finished_at?: string;
        };
        AgentDetail: components["schemas"]["AgentFleetEntry"] & {
            recent_upgrades?: components["schemas"]["AgentUpgrade"][];
        };
        UpgradeRequest: {
            agent_ids?: string[];
            /** @description every outdated, upgrade-capable agent of the tenant */
            all_outdated?: boolean;
        } & (unknown | unknown);
        UpgradeBatchResult: {
            target_version?: string;
            created?: components["schemas"]["AgentUpgrade"][];
            skipped?: {
                agent_id?: string;
                /** @enum {string} */
                reason?: "up_to_date" | "upgrade_active" | "manual_upgrade_required" | "unsupported" | "no_release_for_platform" | "not_found";
            }[];
        };
        AgentUpgradeList: {
            items?: components["schemas"]["AgentUpgrade"][];
            next_cursor?: string;
        };
        UpgradePolicy: {
            enabled: boolean;
            window_start: string;
            /** @description may wrap past midnight; equal to window_start = the whole day */
            window_end: string;
            /** @description IANA name, validated with time.LoadLocation */
            timezone: string;
            max_concurrent: number;
            /** @description "" = platform current; otherwise a stored release version (a lower pin downgrades newer agents) */
            target_version: string;
            readonly paused?: boolean;
            readonly paused_reason?: string;
            readonly updated_by?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        AutoEnrollSwitch: {
            enabled: boolean;
        };
        AutoEnroll: {
            enabled?: boolean;
            updated_by?: string;
            /** Format: date-time */
            updated_at?: string | null;
            /** @description accepted clock skew of a proof timestamp */
            window_seconds?: number;
            keys?: components["schemas"]["AutoEnrollKey"][];
        };
        AutoEnrollKey: {
            /** Format: uuid */
            id?: string;
            /** @description public id agents send */
            key_id?: string;
            name?: string;
            allowed_cidrs?: string[];
            enabled?: boolean;
            /** @enum {string} */
            state?: "active" | "disabled" | "expired" | "exhausted";
            /** Format: date-time */
            expires_at?: string | null;
            /** @description 0 = unlimited */
            max_enrollments?: number;
            enrollments?: number;
            /** Format: date-time */
            last_used_at?: string | null;
            last_used_ip?: string;
            created_by?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AutoEnrollKeySecret: {
            key?: components["schemas"]["AutoEnrollKey"];
            /** @description aks_…; shown once, never stored in clear */
            secret?: string;
        };
        AutoEnrollKeyCreate: {
            name: string;
            /** @description networks agents may enroll from (a bare address is a single host; /0 is refused) */
            allowed_cidrs: string[];
            enabled?: boolean;
            /** Format: date-time */
            expires_at?: string | null;
            max_enrollments?: number;
        };
        AutoEnrollKeyUpdate: {
            name?: string;
            allowed_cidrs?: string[];
            enabled?: boolean;
            /**
             * Format: date-time
             * @description null removes the expiry
             */
            expires_at?: string | null;
            max_enrollments?: number;
        };
        AgentReleaseInfo: {
            version?: string;
            /** @enum {string} */
            source?: "bundled" | "import";
            key_id?: string;
            /** Format: date-time */
            imported_at?: string;
            platforms?: {
                os?: string;
                arch?: string;
                install_type?: string;
                size?: number;
            }[];
        };
        AgentReleaseList: {
            current_version?: string;
            items?: components["schemas"]["AgentReleaseInfo"][];
        };
    };
    responses: never;
    parameters: {
        csrf: string;
        /** @example 018f3a2b-0000-7000-8000-000000000001 */
        id: string;
        /** @example 018f3a2b-0000-7000-8000-0000000000aa */
        hostId: string;
        /** @example 018f3a2b-0000-7000-8000-000000000002 */
        other: string;
        cursor: string;
        limit: number;
        upgradeState: "up_to_date" | "available" | "pending" | "in_progress" | "failed" | "rolled_back" | "manual_upgrade_required" | "unsupported";
        requestState: "pending" | "delivered" | "downloading" | "installing" | "succeeded" | "failed" | "rolled_back" | "expired" | "cancelled";
        outdated: boolean;
        agentIdQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listHosts: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["cursor"];
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description host */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteHost: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHostLatestSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setHostTags: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description tagged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retireHost: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description retired */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listHostSnapshots: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["cursor"];
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listHostChanges: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description changes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSnapshot: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    diffSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
                /** @example 018f3a2b-0000-7000-8000-000000000002 */
                other: components["parameters"]["other"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description diff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAgents: {
        parameters: {
            query?: {
                state?: components["parameters"]["upgradeState"];
                outdated?: components["parameters"]["outdated"];
                cursor?: components["parameters"]["cursor"];
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description agent fleet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentFleet"];
                };
            };
        };
    };
    listAgentUpgrades: {
        parameters: {
            query?: {
                state?: components["parameters"]["requestState"];
                agent_id?: components["parameters"]["agentIdQuery"];
                cursor?: components["parameters"]["cursor"];
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description upgrade requests, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentUpgradeList"];
                };
            };
        };
    };
    requestAgentUpgrades: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpgradeRequest"];
            };
        };
        responses: {
            /** @description requests created (delivered to online agents) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpgradeBatchResult"];
                };
            };
            /** @description invalid_argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no_release_available */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description body_too_large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelAgentUpgrade: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentUpgrade"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_cancellable */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAgentUpgradePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpgradePolicy"];
                };
            };
        };
    };
    updateAgentUpgradePolicy: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpgradePolicy"];
            };
        };
        responses: {
            /** @description stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpgradePolicy"];
                };
            };
            /** @description invalid_argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description unknown_version */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description body_too_large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resumeAgentUpgradePolicy: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpgradePolicy"];
                };
            };
        };
    };
    getAutoEnroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description settings and keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoEnroll"];
                };
            };
        };
    };
    setAutoEnroll: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoEnrollSwitch"];
            };
        };
        responses: {
            /** @description stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createAutoEnrollKey: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoEnrollKeyCreate"];
            };
        };
        responses: {
            /** @description created: {key, secret} */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoEnrollKeySecret"];
                };
            };
            /** @description conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAutoEnrollKey: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAutoEnrollKey: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoEnrollKeyUpdate"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoEnrollKey"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rotateAutoEnrollKey: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description rotated: {key, secret} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoEnrollKeySecret"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAgentReleases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description agent releases, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentReleaseList"];
                };
            };
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description agent with recent upgrades */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mintEnrollmentToken: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description token minted (secret returned once) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshInventory: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-0000000000aa */
                host_id: components["parameters"]["hostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description refresh requested */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revokeAgent: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTenantStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description tenant statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSystemStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description system statistics (admin) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportBackup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    importBackup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description imported */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE event stream (agent-online/offline, snapshot-received) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
